# -*- coding: utf-8 -*-
"""ml-string-to-int-encoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSaqzmvPnFVWqNzzDHbhXxQgmFerr0lv
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

Data = pd.read_csv("/content/disney_princess_popularity_dataset_300_rows.csv")

Data

Data.isnull().sum()

# Hear exising Larg number of NAN values(nulls) and categorical) values.

# Next Step is encode the  NAN and Categorical values

# Find columns with string (object) data type
string_columns = Data.select_dtypes(include=['object']).columns.tolist()

print("String columns:", string_columns)

# Step to convert Categorical values in to numerical
list__encode_columns = ('PrincessName', 'FirstMovieTitle', 'HasSoloSong', 'HasDuet', 'HairColor', 'EyeColor', 'OutfitPrimaryColor', 'OutfitStyleEra', 'IsRoyalByBirth', 'HasAnimalSidekick', 'SidekickType', 'HasMagicalPowers', 'MagicType', 'MainSetting', 'IsBasedOnRealStory', 'CulturalOrigin', 'SpeaksToAnimals', 'FightsVillainDirectly', 'RomanticSubplot', 'MarriedByEnd', 'VillainName', 'VillainType', 'Top3Hashtags', 'IsIconic')

for col in list__encode_columns:
    Data[col] = le.fit_transform(Data[col])

Data